# -*- coding: utf-8 -*-
"""KKG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x44ep9oi3dhYl7EkltlPkjhWw-Ty284H
"""

import pandas as pd
import numpy as np

# 1. Load the provided dataset
df_cars = pd.read_csv('Cars Datasets 2025.csv', encoding='latin1')

# 2. Clean the 'CC/Battery Capacity' column to extract numeric Engine Capacity
def extract_cc(x):
    if pd.isna(x): return np.nan
    s = str(x).lower().replace(',', '').replace('cc', '').strip()
    try:
        return float(s)
    except:
        return np.nan

df_cars['Engine Capacity'] = df_cars['CC/Battery Capacity'].apply(extract_cc)
df_cars = df_cars.dropna(subset=['Engine Capacity'])

# 3. Create the Four-Wheeler dataframe using real data from your CSV
np.random.seed(42)
four_wheelers = pd.DataFrame({
    'Engine Capacity': df_cars['Engine Capacity'].sample(100, replace=True).values,
    'Number of Wheels': 4,
    'Weight (kg)': np.random.uniform(1000, 2500, 100), # Adding realistic car weights
    'Vehicle Type': 'four-wheeler'
})

# 4. Synthesize Two-wheelers and Three-wheelers to fulfill the problem statement
two_wheelers = pd.DataFrame({
    'Engine Capacity': np.random.uniform(50, 400, 100),
    'Number of Wheels': 2,
    'Weight (kg)': np.random.uniform(100, 250, 100),
    'Vehicle Type': 'two-wheeler'
})

three_wheelers = pd.DataFrame({
    'Engine Capacity': np.random.uniform(150, 600, 100),
    'Number of Wheels': 3,
    'Weight (kg)': np.random.uniform(300, 600, 100),
    'Vehicle Type': 'three-wheeler'
})

# 5. Combine everything into one master dataset
dataset = pd.concat([two_wheelers, three_wheelers, four_wheelers], ignore_index=True)
print(dataset.head())

"""Task 2: Clean, Preprocess Dataset, and Encode Categorical Variables"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# 1. Separate Features (X) and Target (y)
X = dataset[['Engine Capacity', 'Number of Wheels', 'Weight (kg)']]
y = dataset['Vehicle Type']

# 2. Encode Categorical Target Variable
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# 3. Split dataset into Training (80%) and Testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# 4. Feature Scaling (Crucial for SVMs)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""Task 3: Train Classification Model (SVM)"""

from sklearn.svm import SVC

# Initialize and train the Support Vector Machine Model
svm_model = SVC(kernel='linear', C=1.0, random_state=42)
svm_model.fit(X_train_scaled, y_train)

print("Model Training Complete.")

"""Task 4: Evaluate Model Accuracy Using Test Dataset"""

from sklearn.metrics import accuracy_score, classification_report

# Predict the test set
y_pred = svm_model.predict(X_test_scaled)

# Calculate Accuracy
acc = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {acc * 100:.2f}%\n")

# Detailed Classification Report
target_names = le.classes_
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=target_names))

"""Task 5: Visualize Classification Results Using Charts"""

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
import itertools
plt.style.use('default')
# --- Plot 1: Advanced Pairplot --
dataset['Target'] = y_encoded
plt.figure(figsize=(10, 8))
sns.pairplot(dataset, vars=['Engine Capacity', 'Weight (kg)', 'Number of Wheels'],
             hue='Vehicle Type', palette=['red', 'green', 'blue'], markers=["o", "s", "D"])
plt.suptitle('Pairwise Feature Relationships', y=1.02, fontsize=16)
plt.show()
# --- Plot 2: 3D Feature Distribution --
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')
colors = ['r', 'g', 'b']
for i, t in enumerate(le.classes_):
    idx = (dataset['Vehicle Type'] == t)
    ax.scatter(dataset.loc[idx, 'Engine Capacity'],
               dataset.loc[idx, 'Weight (kg)'],
               dataset.loc[idx, 'Number of Wheels'],
               c=colors[i], label=t, s=50, alpha=0.7)
ax.set_xlabel('Engine Capacity (cc)')
ax.set_ylabel('Weight (kg)')
ax.set_zlabel('Number of Wheels')
ax.set_title('3D Feature Distribution')
ax.legend(prop={'size': 14})
plt.show()
# --- Plot 3: Confusion Matrix --
def plot_confusion_matrix(cm, classes, title='Confusion Matrix', cmap=plt.cm.Blues):
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title, fontsize=20)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45, fontsize=12)
    plt.yticks(tick_marks, classes, fontsize=12)
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], 'd'),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black", fontsize=14)
    plt.ylabel('True label', fontsize=16)
    plt.xlabel('Predicted label', fontsize=16)
    plt.tight_layout()
cnf_matrix = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
plot_confusion_matrix(cnf_matrix, classes=le.classes_)

